In [2]:
import numpy as np

In [3]:
reca = np.array([(1,(.6,.9),'Hel'),(2,(1.3,1.4),'Hey')],dtype=[('x',np.int32),('y',np.float64,2),('z',np.str,4)])

In [4]:
reca

array([(1, [0.6, 0.9], 'Hel'), (2, [1.3, 1.4], 'Hey')],
      dtype=[('x', '<i4'), ('y', '<f8', (2,)), ('z', '<U4')])

In [5]:
reca[0]

(1, [0.6, 0.9], 'Hel')

In [6]:
reca['x']

array([1, 2])

In [7]:
reca['z']

array(['Hel', 'Hey'], dtype='<U4')

In [8]:
reca['y']

array([[0.6, 0.9],
       [1.3, 1.4]])

In [9]:
reca[0]['x']

1

In [10]:
reca['x'][0]

1

In [11]:
reca['y'][0]

array([0.6, 0.9])

In [12]:
reca['y'][1]

array([1.3, 1.4])

In [13]:
reca['z'][1]

'Hey'

In [14]:
np.datetime64('2015')

numpy.datetime64('2015')

In [15]:
np.datetime64('1997-07-08')

numpy.datetime64('1997-07-08')

In [16]:
np.datetime64('1997-07-08 04:00:40' )

numpy.datetime64('1997-07-08T04:00:40')

In [17]:
np.datetime64('1997-07-08 04:30:56+0530')

C:\Users\Radhey Jangid\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  """Entry point for launching an IPython kernel.


numpy.datetime64('1997-07-07T23:00:56')

In [18]:
np.datetime64('1997-07-08 04:30:56+0700')

C:\Users\Radhey Jangid\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  """Entry point for launching an IPython kernel.


numpy.datetime64('1997-07-07T21:30:56')

In [19]:
np.datetime64('1997-07-08') == np.datetime64('1997-07-08')

True

In [20]:
np.datetime64('1997')

numpy.datetime64('1997')

In [21]:
np.datetime64('1997')


AttributeError: 'numpy.datetime64' object has no attribute 'byfloat'